services: 
  postgres: 
    image: timescale/timescaledb:latest-pg17
    ports:
      - "5432:5432"
    mem_limit: 512M
    env_file:
      - .env
    volumes:
      - ./pg_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
    - "6379:6379"
    network_mode: "host"
    restart: unless-stopped

  portfolio-manager:
    depends_on: 
      - postgres
    env_file:
      - .env
    build:
      context: ./app

  data-gateway: 
    depends_on:
      - redis

    network_mode: host
    env_file:
      - .env
    build:
      context: ./app
    command: ["python3", "data-gateway.py"]
  
