services: 
  postgres: 
    image: timescale/timescaledb:latest-pg17
    ports:
      - "5432:5432"
    mem_limit: 512M
    env_file:
      - .env
    volumes:
      - ./pg_data:/var/lib/postgresql/data

  
  portfolio-manager:
    depends_on: 
      - postgres
    env_file:
      - .env
    build:
      context: ./app
    
