services: 

  redis:
    image: redis:latest
    ports: 
      - "6379:6379"
    restart: always
    cpuset: "3"
    network_mode: host
    volumes: 
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 10s
      retries: 5

  postgres: 
    image: timescale/timescaledb:latest-pg17
    ports:
      - "5432:5432"
    mem_limit: 512M
    env_file:
      - .env
    volumes:
      - ./pg_data:/var/lib/postgresql/data

  portfolio-manager:
    depends_on: 
      - postgres
    env_file:
      - .env
    build:
      context: ./app
    command:
      ["./portfolio-manager.sh"]

  data-gateway: 
    depends_on:
      - redis
    build:
      context: ./app
    network_mode: host
    env_file:
      - .env
    cpuset: "2"
    command: ["python3", "data-gateway.py"]
    volumes:
      - ./subscriptions.yaml:/app/subscriptions.yaml

  trading-bot:
    depends_on:
      - redis
      - data-gateway
    build:
      context: ./app

    network_mode: host
    env_file:
      - .env
    cpuset: "1"
    command: ["python3", "main.py"]
  
volumes:
  redis_data: