services: 
  postgres: 
    image: timescale/timescaledb:latest-pg17
    ports:
      - "5432:5432"
    mem_limit: 512M
    env_file:
      - .env
    volumes:
      - ./pg_data:/var/lib/postgresql/data

  redis:
    # image: redis:latest
    image: valkey/valkey:latest # valkey 
    # network_mode: "host"
    cpuset: "3"
    ports:
      - 6379:6379
    restart: unless-stopped

  portfolio-manager:
    depends_on: 
      - postgres
    env_file:
      - .env
    build:
      context: ./app

  data-gateway: 
    depends_on:
      - redis

    network_mode: host
    env_file:
      - .env
    build:
      context: ./app
    cpuset: "2"
    command: ["python3", "data-gateway.py"]
    volumes:
      - ./subscriptions.yaml:/app/subscriptions.yaml
  
