services: 
  db:
    image: postgres:15
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 3s
      retries: 3
    volumes: 
      - pgdata:/var/lib/postgresql/data
    env_file:
     - .env

  redis:
    image: redis:7
    ports: 
      - "6379:6379"
    restart: always
    networks:
      - default
    volumes: 
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 10s
      retries: 5

