services: 

  redis:
    image: redis:latest
    ports: 
      - "6379:6379"
    restart: always
    networks:
      - default
    volumes: 
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 10s
      retries: 5

volumes:
  redis_data: